apiVersion: v1
kind: Service
metadata:
  name: dns-lb
spec:
  type: LoadBalancer
  selector:
    app: dns
  ports:
  - name: webgui-dns
    port: 5000
    targetPort: 5000
  - name: dns-api
    port: 5001
    targetPort: 5001
